version: '3.8'
services:

  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true   # TODO: required because of vboxnetctl, can I use setcap instead?
    network_mode: host # TODO: this requires a "jenkins" entry in my host's /etc/hosts file, I don't like that but it's required to use vboxnetctl
    volumes:
      - ${JENKINS_HOME:-./jenkins_home}:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp:rw
    devices:
      - "/dev/vboxdrv:/dev/vboxdrv"
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      #- JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: false
    network_mode: host # TODO: this requires a "jenkins" entry in my host's /etc/hosts file, I don't like that but it's required to use vboxnetctl
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS:-./logs/nginx/jenkins}:/var/log/nginx/jenkins
      #- ${NGINX_SSL:-./ssl}:/etc/ssl:ro
    restart: always
